# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.valida_extension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de Usuario')),
                ('rut', models.CharField(max_length=9, unique=True, verbose_name='RUT')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidoPaterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('avatar', models.ImageField(blank=True, max_length=500, null=True, upload_to='uploads/avatar/', validators=[users.valida_extension.valid_extension_image], verbose_name='Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1, verbose_name='Est\xe1 Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Pertenece al Staff de Administradores')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='loginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.DateTimeField(auto_now_add=True, verbose_name='Logueado el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Historial de Login',
            },
        ),
    ]
